name: game_bot_with_ai
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  logger: ^1.1.0
  dio: ^4.0.6
  teledart: ^0.3.4
  cloudinary_sdk: ^4.0.2+10
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
